name: backend-test
version: 0.0.0.1
github: "hrajchert/backend-test"
license: BSD3
author: "Hernan Rajchert"
maintainer: "hrajchert@gmail.com"
copyright: "2020 Hernan Rajchert"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/backend-test#readme>

dependencies:
  - base >= 4.7 && < 5
  - hw-kafka-client
  - hw-kafka-avro
  - avro
  - bytestring
  - containers
  - text
  - wreq
  - time
  - aeson
  - servant-server
  - servant
  - wai
  - warp

library:
  source-dirs: src

executables:
  servant-server-exe:
    main: Main.hs
    source-dirs: app/ServantServer
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend-test

  test-producer-exe:
    main: Main.hs
    source-dirs: app/TestProducer
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend-test

tests:
  backend-test-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend-test
